#image: registry.coinninja.net/engineering/android-sdk:latest
image: registry.coinninja.net/engineering/android-ndk:tooling-update

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  GRADLE_OPTS: "-Dorg.gradle.daemon=true"

stages:
  - test
  - build
  - deploy

before_script:
  - chmod +x ./gradlew
  - ./gradlew --version
  - ./gradlew --status
  - export ANDROID_HOME=/sdk-tools/
  - export PATH=$PATH:/sdk-tools/platform-tools/
  - export APP_VERSION=`./sh/appversion_lookup.sh $HOCKEY_APP_API_TOKEN`
  - echo $APP_VERSION
  - echo "${__google_services_json}" | base64 -d > ./app/google-services.json

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

.build_and_sign: &build_and_sign
  before_script:
    - export APP_VERSION=`./sh/appversion_lookup.sh $HOCKEY_APP_API_TOKEN`
    - echo $APP_VERSION
    - export DB_CI_RUNNER=true
    - export ANDROID_HOME=/sdk-tools/
    - export PATH=$PATH:/sdk-tools/platform-tools/
    - chmod +x ./gradlew
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.coinninja.net/cn/coin-keeper-android-code-signing.git /tmp/secret
    - mv /tmp/secret/*.enc app/
    - echo "${__google_services_json}" | base64 -d > ./app/google-services.json
    - echo "${__key_encryption_key}" | base64 -d > /tmp/secret/key
    - echo "${__playstore_service_key}" | base64 -d > ./google_play.json
    - openssl enc -d -aes-256-cbc -kfile /tmp/secret/key -in app/keystore.properties.enc -out app/keystore.properties
    - openssl enc -d -aes-256-cbc -kfile /tmp/secret/key -in app/coinkeeper-release.jks.enc -out app/coinkeeper-release.jks
    - export PREVIOUS_DEPLOY_COMMIT=`sh/gitlab_deploys.sh -t "${API_TOKEN}"`

test-dropbit:
  stage: test
  tags:
    - large
  script:
    - ./gradlew app:testProductionDebugUnitTest
  artifacts:
    when: always
    expire_in: '8 hours'
    paths:
      - ./app/build/outputs/apk/production/debug/*.apk
      - ./app/build/outputs/apk/staging/debug/*.apk

lint-dropbit:
  stage: build
  tags:
    - android
  script:
    - ./gradlew app:lintProductionDebug

assemble-dropbit:
  stage: build
  tags:
    - android
  script:
    - ./gradlew app:assembleDebug
  artifacts:
    when: always
    expire_in: '8 hours'
    paths:
      - ./app/build/outputs/apk/production/debug/*.apk
      - ./app/build/outputs/apk/staging/debug/*.apk

test-common:
  stage: test
  tags:
    - android
  script:
    - ./gradlew common:lintRelease common:testReleaseUnitTest
  artifacts:
    when: always
    expire_in: '8 hours'
    paths:
      - ./common/build/outputs/aar/*.aar

test-twitter:
  stage: test
  tags:
    - android
  script:
    - ./gradlew twitter:lintRelease twitter:testReleaseUnitTest
  artifacts:
    when: always
    expire_in: '8 hours'
    paths:
      - ./twitter/build/outputs/aar/*.aar

test-persistance:
  stage: test
  tags:
    - android
  script:
    - ./gradlew persistance:lintRelease persistance:testReleaseUnitTest
  artifacts:
    when: always
    expire_in: '8 hours'
    paths:
      - ./persistance/build/outputs/aar/*.aar


test-thunderdome:
  stage: test
  tags:
    - android
  script:
    - ./gradlew thunderdome:lintRelease thunderdome:testReleaseUnitTest
  artifacts:
    when: always
    expire_in: '8 hours'
    paths:
      - ./thunderdome/build/outputs/aar/*.aar

release-candidate:
  stage: deploy
  script:
    - ./gradlew assembleProduction
  environment:
    name: internal
  tags:
    - android
  artifacts:
    name: "manualInstallableAPK-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: '8 hours'
    paths:
      - ./app/build/outputs/apk/production/**/*.apk
  <<: *build_and_sign
  only:
    - develop@cn/dropbit-android
    - /^[\d\.]+RC$/@cn/dropbit-android

production-debug:
  stage: deploy
  script:
    - ./gradlew uploadProductionDebugToHockeyApp
  only:
    - develop@cn/dropbit-android
    - /^[\d\.]+RC$/@cn/dropbit-android
  tags:
    - android
  environment:
    name: internal
  artifacts:
    name: "manualInstallableAPK-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: '8 hours'
    paths:
      - ./app/build/outputs/apk/production/debug/*.apk

staging-debug:
  stage: deploy
  script:
    - ./gradlew uploadStagingDebugToHockeyApp
  only:
    - develop@cn/dropbit-android
    - /^[\d\.]+RC$/@cn/dropbit-android
  tags:
    - android
  environment:
    name: internal
  artifacts:
    name: "manualInstallableAPK-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: '8 hours'
    paths:
      - ./app/build/outputs/apk/production/debug/*.apk

regtest-debug:
  stage: deploy
  script:
    - ./gradlew uploadRegtestDebugToHockeyApp
  only:
    - develop@cn/dropbit-android
    - /^[\d\.]+RC$/@cn/dropbit-android
  tags:
    - android
  environment:
    name: internal
  artifacts:
    name: "manualInstallableAPK-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: '8 hours'
    paths:
      - ./app/build/outputs/apk/production/debug/*.apk
