package com.coinninja.coinkeeper.db.migrations

import android.database.sqlite.SQLiteDatabase
import com.coinninja.coinkeeper.db.AbstractMigration
import com.coinninja.coinkeeper.db.Migration
import org.greenrobot.greendao.database.Database

class Migrate_V38_to_V39 : AbstractMigration() {
    override val previousMigration: Migration = Migrate_V37_to_V38()
    override val migratedVersion: Int = 39
    override val targetVersion: Int = 38

    override fun applyMigration(db: Database, currentVersion: Int) {
        db.execSQL("CREATE TABLE IF NOT EXISTS `LEDGER_SETTLEMENT` (`_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `INVOICE_ID` INTEGER, `TO_USER_IDENTITY_ID` INTEGER, `FROM_USER_IDENTITY_ID` INTEGER, `INVITE_ID` INTEGER, `NOTIFICATION_ID` INTEGER, `CREATED_AT` TEXT, FOREIGN KEY(`TO_USER_IDENTITY_ID`) REFERENCES `USER_IDENTITY`(`_id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`FROM_USER_IDENTITY_ID`) REFERENCES `USER_IDENTITY`(`_id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`INVITE_ID`) REFERENCES `INVITE_TRANSACTION_SUMMARY`(`_id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`INVOICE_ID`) REFERENCES `LIGHTNING_INVOICE`(`_id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`NOTIFICATION_ID`) REFERENCES `TRANSACTION_NOTIFICATION`(`_id`) ON UPDATE NO ACTION ON DELETE CASCADE )")
        db.execSQL("CREATE  INDEX `LEDGER_SETTLEMENT__TO_USER_IDENTITY_ID` ON `LEDGER_SETTLEMENT` (`TO_USER_IDENTITY_ID`)")
        db.execSQL("CREATE  INDEX `LEDGER_SETTLEMENT__FROM_USER_IDENTITY_ID` ON `LEDGER_SETTLEMENT` (`FROM_USER_IDENTITY_ID`)")
        db.execSQL("CREATE  INDEX `LEDGER_SETTLEMENT__INVITE_ID` ON `LEDGER_SETTLEMENT` (`INVITE_ID`)")
        db.execSQL("CREATE  INDEX `LEDGER_SETTLEMENT__INVOICE_ID` ON `LEDGER_SETTLEMENT` (`INVOICE_ID`)")
        db.execSQL("CREATE  INDEX `LEDGER_SETTLEMENT__NOTIFICATION_ID` ON `LEDGER_SETTLEMENT` (`NOTIFICATION_ID`)")
        db.execSQL("INSERT OR REPLACE INTO room_master_table (id,identity_hash) VALUES(42, 'ef2f191257894f7de8666858a5f9a7d9')")
        db.execSQL("insert into `LEDGER_SETTLEMENT` (`INVOICE_ID`,`CREATED_AT`) select `_id`, `CREATED_AT` from `LIGHTNING_INVOICE`")
    }
}
