package com.coinninja.coinkeeper.db.schema;

import org.greenrobot.greendao.database.Database;

public class V34_Schema {
    public static final int SCHEMA_VERSION = 34;

    public void create(Database db) {
        db.execSQL("CREATE TABLE \"ACCOUNT\" (\"_id\" INTEGER PRIMARY KEY ,\"WALLET_ID\" INTEGER,\"CN_WALLET_ID\" TEXT,\"CN_USER_ID\" TEXT,\"STATUS\" INTEGER,\"PHONE_NUMBER_HASH\" TEXT,\"PHONE_NUMBER\" TEXT,\"VERIFICATION_TTL\" INTEGER NOT NULL ,\"IS_PRIVATE\" INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE \"ADDRESS\" (\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ,\"ADDRESS\" TEXT UNIQUE ,\"WALLET_ID\" INTEGER,\"INDEX\" INTEGER NOT NULL ,\"CHANGE_INDEX\" INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE \"BROADCAST_BTC_INVITE\" (\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ,\"BROADCAST_TX_ID\" TEXT UNIQUE ,\"BTC_STATE\" INTEGER,\"BROADCAST_TO_ADDRESS\" TEXT,\"INVITE_SERVER_ID\" TEXT UNIQUE ,\"INVITE_TRANSACTION_SUMMARY_ID\" INTEGER)");
        db.execSQL("CREATE TABLE \"CONTACT\" (\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ,\"PHONE_NUMBER_HASH\" TEXT)");
        db.execSQL("CREATE TABLE \"EXTERNAL_NOTIFICATION\" (\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ,\"MESSAGE\" TEXT UNIQUE ,\"EXTRA_DATA\" TEXT)");
        db.execSQL("CREATE TABLE \"FUNDING_STAT\" (\"_id\" INTEGER PRIMARY KEY ,\"ADDRESS_ID\" INTEGER,\"TSID\" INTEGER,\"WALLET_ID\" INTEGER,\"ADDR\" TEXT,\"POSITION\" INTEGER NOT NULL ,\"VALUE\" INTEGER NOT NULL ,\"TARGET_ID\" INTEGER,\"FUNDED_TRANSACTION\" TEXT,\"STATE\" INTEGER)");
        db.execSQL("CREATE TABLE \"INTERNAL_NOTIFICATION\" (\"PRIORITY\" INTEGER,\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ,\"MESSAGE\" TEXT,\"HAS_BEEN_SEEN\" INTEGER NOT NULL ,\"MESSAGE_LEVEL\" INTEGER,\"SERVER_UUID\" TEXT,\"CLICK_ACTION\" TEXT,\"WALLET_ID\" INTEGER)");
        db.execSQL("CREATE TABLE \"TARGET_STAT\" (\"_id\" INTEGER PRIMARY KEY ,\"ADDRESS_ID\" INTEGER,\"TSID\" INTEGER,\"WALLET_ID\" INTEGER,\"ADDR\" TEXT,\"POSITION\" INTEGER NOT NULL ,\"VALUE\" INTEGER NOT NULL ,\"TX_TIME\" INTEGER NOT NULL ,\"FUNDING_ID\" INTEGER,\"STATE\" INTEGER)");
        db.execSQL("CREATE TABLE \"TRANSACTION_SUMMARY\" (\"_id\" INTEGER PRIMARY KEY ,\"TXID\" TEXT UNIQUE ,\"TRANSACTIONS_INVITES_SUMMARY_ID\" INTEGER,\"SOUGHT_NOTIFICATION\" INTEGER NOT NULL ,\"WALLET_ID\" INTEGER NOT NULL ,\"FEE\" INTEGER NOT NULL ,\"TX_TIME\" INTEGER NOT NULL ,\"NUM_CONFIRMATIONS\" INTEGER NOT NULL ,\"BLOCKHASH\" TEXT,\"NUM_INPUTS\" INTEGER NOT NULL ,\"NUM_OUTPUTS\" INTEGER NOT NULL ,\"BLOCKHEIGHT\" INTEGER NOT NULL ,\"HISTORIC_PRICE\" INTEGER NOT NULL ,\"TRANSACTION_NOTIFICATION_ID\" INTEGER,\"MEM_POOL_STATE\" INTEGER)");
        db.execSQL("CREATE TABLE \"USER\" (\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ,\"PIN\" TEXT,\"UID\" TEXT,\"COMPLETED_TRAINING\" INTEGER NOT NULL ,\"LOCKED_UNTIL_TIME\" INTEGER NOT NULL )");
        db.execSQL("CREATE TABLE \"WALLET\" (\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ,\"HD_INDEX\" INTEGER NOT NULL ,\"USER_ID\" INTEGER,\"LAST_SYNC\" INTEGER NOT NULL ,\"INTERNAL_INDEX\" INTEGER NOT NULL ,\"EXTERNAL_INDEX\" INTEGER NOT NULL ,\"BALANCE\" INTEGER NOT NULL ,\"SPENDABLE_BALANCE\" INTEGER NOT NULL ,\"BLOCK_TIP\" INTEGER NOT NULL ,\"LAST_USDPRICE\" INTEGER NOT NULL ,\"LAST_FEE\" TEXT)");
        db.execSQL("CREATE TABLE \"WORD\" (\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ,\"WALLET_ID\" INTEGER,\"WORD\" TEXT,\"SORT_ORDER\" INTEGER NOT NULL )");

        // changed in v33-v34
        db.execSQL("CREATE TABLE \"USER_IDENTITY\" (\"_id\" INTEGER PRIMARY KEY , \"IDENTITY\" TEXT UNIQUE , \"TYPE\" INTEGER, \"DISPLAY_NAME\" TEXT, \"HANDLE\" TEXT, \"HASH\" TEXT, \"AVATAR\" TEXT);");
        db.execSQL("CREATE TABLE \"DROPBIT_ME_IDENTITY\" (\"_id\" INTEGER PRIMARY KEY , \"TYPE\" INTEGER, \"IDENTITY\" TEXT, \"SERVER_ID\" TEXT UNIQUE , \"HANDLE\" TEXT, \"HASH\" TEXT, \"STATUS\" INTEGER, \"ACCOUNT_ID\" INTEGER);");
        db.execSQL("CREATE TABLE \"TRANSACTION_NOTIFICATION\" ( \"_id\" INTEGER PRIMARY KEY , \"MEMO\" TEXT, \"IS_SHARED\" INTEGER NOT NULL , \"AMOUNT\" INTEGER NOT NULL , \"AMOUNT_CURRENCY\" TEXT, \"TXID\" TEXT, \"TO_USER_IDENTITY_ID\" INTEGER, \"FROM_USER_IDENTITY_ID\" INTEGER);");
        db.execSQL("CREATE TABLE \"TRANSACTIONS_INVITES_SUMMARY\" ( \"_id\" INTEGER PRIMARY KEY AUTOINCREMENT , \"TRANSACTION_SUMMARY_ID\" INTEGER, \"TO_USER_IDENTITY_ID\" INTEGER, \"FROM_USER_IDENTITY_ID\" INTEGER, \"INVITE_SUMMARY_ID\" INTEGER, \"INVITE_TIME\" INTEGER NOT NULL , \"BTC_TX_TIME\" INTEGER NOT NULL , \"TRANSACTION_TX_ID\" TEXT, \"INVITE_TX_ID\" TEXT);");
        db.execSQL("CREATE TABLE \"INVITE_TRANSACTION_SUMMARY\" ( \"TO_USER_IDENTITY_ID\" INTEGER, \"FROM_USER_IDENTITY_ID\" INTEGER, \"WALLET_ID\" INTEGER, \"TRANSACTIONS_INVITES_SUMMARY_ID\" INTEGER, \"TRANSACTION_NOTIFICATION_ID\" INTEGER, \"_id\" INTEGER PRIMARY KEY AUTOINCREMENT , \"TYPE\" INTEGER, \"BTC_STATE\" INTEGER, \"SERVER_ID\" TEXT UNIQUE , \"BTC_TRANSACTION_ID\" TEXT, \"SENT_DATE\" INTEGER, \"ADDRESS\" TEXT, \"PUBKEY\" TEXT, \"VALUE_SATOSHIS\" INTEGER, \"VALUE_FEES_SATOSHIS\" INTEGER, \"HISTORIC_VALUE\" INTEGER NOT NULL );");
    }
}
